[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_glob = ['notebooks/**']

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
exclude = '''
/notebooks/
'''